# Generated by Django 5.0.6 on 2024-06-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nid_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_no',
        ),
    ]
