# Generated by Django 5.0.6 on 2024-11-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
